spring.application.name=BudgetStock
server.port=8064

spring.datasource.url=jdbc:mysql://localhost:3306/db_budget_stock?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==== HIKARI POOL CONFIG ====
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=20

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ==== SECURITY (JWT Bearer) ====
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

jwt.refresh-token.expiration=604800000
rsa.publickey=classpath:keys/publicKey.pem
rsa.privatekey=classpath:keys/privateKey.pem


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true