apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-frontend
  labels:
    app: stock-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-frontend
  template:
    metadata:
      labels:
        app: stock-frontend
    spec:
      containers:
        - name: stock-frontend
          image: stock-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stock-frontend
spec:
  selector:
    app: stock-frontend
  ports:
    - protocol: TCP
      port: 3000    # exposed to user
      targetPort: 80  # port inside container
  type: LoadBalancer