apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-fournisseur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-fournisseur
  template:
    metadata:
      labels:
        app: service-fournisseur
    spec:
      containers:
        - name: service-fournisseur
          image: fournisseur-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "hanae"
            - name: DB_NAME
              value: "procurement_system"
            - name: EUREKA_HOST
              value: "discovery-service"
---
apiVersion: v1
kind: Service
metadata:
  name: service-fournisseur
spec:
  selector:
    app: service-fournisseur
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer